### ISSUE TITLE
Comparison with onnx-mlir 

### ISSUE THREAD

**Issue by jamespinkerton** [siboehm/lleaves#33]
Hi. I’m a big fan of the project.

I’m curious how the project benchmarks agains onnx-mlir. Is there a reason lleaves should be more performant?

Thanks so much!

**Comment by siboehm** [comment]
Doesn't look like they support it: see [here](https://github.com/search?q=repo%3Aonnx%2Fonnx-mlir%20TreeEnsembleRegressor&type=code) and [here](https://github.com/onnx/onnx-mlir/issues/1808#issuecomment-1290781369). ONNX Runtime has support for it (as an interpreter obv), but their implementation is mostly optimized for single-batch.

The LightGBM -> ONNX -> Binary pipeline doesn't quite get you model parity, since the `node_thresholds` for the [TreeEnsembleRegressor](https://github.com/onnx/onnx/blob/main/docs/Operators-ml.md#aionnxmltreeensembleregressor) are float32, while LightGBM (and most other libs) use float64, which can (in theory) lead to arbitrary large divergences. Float32 is definitely nicer, reduces the bandwidth bottleneck a bit.

It'd be pretty fun to implement a TreeEnsembleRegressor lowering in onnx-mlir! Maybe I'll do that at some point. There are some fun passes to write, like optimizing LightGBMs bitvector-based categorical branching.
